#!/usr/bin/with-contenv bash
# shellcheck shell=bash

unset AWG_CONFS
rm -rf /run/activeconfs
# Enumerate interfaces
for awgconf in /config/wg_confs/*.conf; do
    if grep -q "\[Interface\]" "${awgconf}"; then
        echo "**** Found AWG conf ${awgconf}, adding to list ****"
        AWG_CONFS+=("${awgconf}")
    else
        echo "**** Found AWG conf ${awgconf}, but it doesn't seem to be valid, skipping. ****"
    fi
done

if [[ -z "${AWG_CONFS[*]}" ]]; then
    echo "**** No valid tunnel config found. Please create a valid config and restart the container ****"
    ip route del default
    exit 0
fi

unset FAILED
for tunnel in "${AWG_CONFS[@]}"; do
    echo "**** Activating tunnel ${tunnel} ****"
    if ! awg-quick up "${tunnel}"; then
        FAILED="${tunnel}"
        break
    fi
done

if [[ -z "${FAILED}" ]]; then
    declare -p AWG_CONFS > /run/activeconfs
    echo "**** All tunnels are now active ****"
else
    echo "**** Tunnel ${FAILED} failed, will stop all others! ****"
    for tunnel in "${AWG_CONFS[@]}"; do
        if [[ "${tunnel}" = "${FAILED}" ]]; then
            break
        else
            echo "**** Disabling tunnel ${tunnel} ****"
            awg-quick down "${tunnel}" || :
        fi
    done
    ip route del default
    echo "**** All tunnels are now down. Please fix the tunnel config ${FAILED} and restart the container ****"
fi
